Name:		postgresql
Version:        9.6.5
Release:        1
Summary:	Vvv        

Group:          Databases
License:        GPL
Source0:	postgresql-%{version}.tar.gz
BuildRoot:      ../BUILDROOT/%{name}-%{version}

Patch1:         00001-1c_FULL_96-0.23.patch
Patch2:         00002-online_analyze.patch
Patch3:         00003-plantuner.patch
Patch4:         00004-postgresql-1c-9.6.patch
Patch5:         00005-exists_opt-2.patch
Patch6:         00006-coalesce_cost-1.patch

%description


%prep
%setup -q 
%patch1 -p1 
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1

%build
./configure --prefix=/usr/%{name}-%{version} --datarootdir=/home/psql/data --without-openssl --without-ldap --without-selinux --with-blocksize=4 --with-wal-blocksize=4
make


%install
rm -rf $RPM_BUILD_ROOT
%makeinstall 


%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,postgres,postgres,-)
%doc
/usr/bin/clusterdb
   /usr/bin/createdb
   /usr/bin/createlang
   /usr/bin/createuser
   /usr/bin/dropdb
   /usr/bin/droplang
   /usr/bin/dropuser
   /usr/bin/ecpg
   /usr/bin/initdb
   /usr/bin/pg_archivecleanup
   /usr/bin/pg_basebackup
   /usr/bin/pg_config
   /usr/bin/pg_controldata
   /usr/bin/pg_ctl
   /usr/bin/pg_dump
   /usr/bin/pg_dumpall
   /usr/bin/pg_isready
   /usr/bin/pg_receivexlog
   /usr/bin/pg_recvlogical
   /usr/bin/pg_resetxlog
   /usr/bin/pg_restore
   /usr/bin/pg_rewind
   /usr/bin/pg_test_fsync
   /usr/bin/pg_test_timing
   /usr/bin/pg_upgrade
   /usr/bin/pg_xlogdump
   /usr/bin/pgbench
   /usr/bin/postgres
   /usr/bin/postmaster
   /usr/bin/psql
   /usr/bin/reindexdb
   /usr/bin/vacuumdb
   /usr/include/ecpg_config.h
   /usr/include/ecpg_informix.h
   /usr/include/ecpgerrno.h
   /usr/include/ecpglib.h
   /usr/include/ecpgtype.h
   /usr/include/informix/esql/datetime.h
   /usr/include/informix/esql/decimal.h
   /usr/include/informix/esql/sqltypes.h
   /usr/include/internal/c.h
   /usr/include/internal/libpq-int.h
   /usr/include/internal/libpq/pqcomm.h
   /usr/include/internal/port.h
   /usr/include/internal/postgres_fe.h
   /usr/include/internal/pqexpbuffer.h
   /usr/include/libpq-events.h
   /usr/include/libpq-fe.h
   /usr/include/libpq/libpq-fs.h
   /usr/include/pg_config.h
   /usr/include/pg_config_ext.h
   /usr/include/pg_config_manual.h
   /usr/include/pg_config_os.h
   /usr/include/pgtypes_date.h
   /usr/include/pgtypes_error.h
   /usr/include/pgtypes_interval.h
   /usr/include/pgtypes_numeric.h
   /usr/include/pgtypes_timestamp.h
   /usr/include/postgres_ext.h
   /usr/include/server/access/amapi.h
   /usr/include/server/access/amvalidate.h
   /usr/include/server/access/attnum.h
   /usr/include/server/access/brin.h
   /usr/include/server/access/brin_internal.h
   /usr/include/server/access/brin_page.h
   /usr/include/server/access/brin_pageops.h
   /usr/include/server/access/brin_revmap.h
   /usr/include/server/access/brin_tuple.h
   /usr/include/server/access/brin_xlog.h
   /usr/include/server/access/clog.h
   /usr/include/server/access/commit_ts.h
   /usr/include/server/access/genam.h
   /usr/include/server/access/generic_xlog.h
   /usr/include/server/access/gin.h
   /usr/include/server/access/gin_private.h
   /usr/include/server/access/gist.h
   /usr/include/server/access/gist_private.h
   /usr/include/server/access/gistscan.h
   /usr/include/server/access/hash.h
   /usr/include/server/access/heapam.h
   /usr/include/server/access/heapam_xlog.h
   /usr/include/server/access/hio.h
   /usr/include/server/access/htup.h
   /usr/include/server/access/htup_details.h
   /usr/include/server/access/itup.h
   /usr/include/server/access/multixact.h
   /usr/include/server/access/nbtree.h
   /usr/include/server/access/parallel.h
   /usr/include/server/access/printtup.h
   /usr/include/server/access/reloptions.h
   /usr/include/server/access/relscan.h
   /usr/include/server/access/rewriteheap.h
   /usr/include/server/access/rmgr.h
   /usr/include/server/access/rmgrlist.h
   /usr/include/server/access/sdir.h
   /usr/include/server/access/skey.h
   /usr/include/server/access/slru.h
   /usr/include/server/access/spgist.h
   /usr/include/server/access/spgist_private.h
   /usr/include/server/access/stratnum.h
   /usr/include/server/access/subtrans.h
   /usr/include/server/access/sysattr.h
   /usr/include/server/access/timeline.h
   /usr/include/server/access/transam.h
   /usr/include/server/access/tsmapi.h
   /usr/include/server/access/tupconvert.h
   /usr/include/server/access/tupdesc.h
   /usr/include/server/access/tupmacs.h
   /usr/include/server/access/tuptoaster.h
   /usr/include/server/access/twophase.h
   /usr/include/server/access/twophase_rmgr.h
   /usr/include/server/access/valid.h
   /usr/include/server/access/visibilitymap.h
   /usr/include/server/access/xact.h
   /usr/include/server/access/xlog.h
   /usr/include/server/access/xlog_fn.h
   /usr/include/server/access/xlog_internal.h
   /usr/include/server/access/xlogdefs.h
   /usr/include/server/access/xloginsert.h
   /usr/include/server/access/xlogreader.h
   /usr/include/server/access/xlogrecord.h
   /usr/include/server/access/xlogutils.h
   /usr/include/server/bootstrap/bootstrap.h
   /usr/include/server/c.h
   /usr/include/server/catalog/binary_upgrade.h
   /usr/include/server/catalog/catalog.h
   /usr/include/server/catalog/catversion.h
   /usr/include/server/catalog/dependency.h
   /usr/include/server/catalog/genbki.h
   /usr/include/server/catalog/heap.h
   /usr/include/server/catalog/index.h
   /usr/include/server/catalog/indexing.h
   /usr/include/server/catalog/namespace.h
   /usr/include/server/catalog/objectaccess.h
   /usr/include/server/catalog/objectaddress.h
   /usr/include/server/catalog/opfam_internal.h
   /usr/include/server/catalog/pg_aggregate.h
   /usr/include/server/catalog/pg_am.h
   /usr/include/server/catalog/pg_amop.h
   /usr/include/server/catalog/pg_amproc.h
   /usr/include/server/catalog/pg_attrdef.h
   /usr/include/server/catalog/pg_attribute.h
   /usr/include/server/catalog/pg_auth_members.h
   /usr/include/server/catalog/pg_authid.h
   /usr/include/server/catalog/pg_cast.h
   /usr/include/server/catalog/pg_class.h
   /usr/include/server/catalog/pg_collation.h
   /usr/include/server/catalog/pg_collation_fn.h
   /usr/include/server/catalog/pg_constraint.h
   /usr/include/server/catalog/pg_constraint_fn.h
   /usr/include/server/catalog/pg_control.h
   /usr/include/server/catalog/pg_conversion.h
   /usr/include/server/catalog/pg_conversion_fn.h
   /usr/include/server/catalog/pg_database.h
   /usr/include/server/catalog/pg_db_role_setting.h
   /usr/include/server/catalog/pg_default_acl.h
   /usr/include/server/catalog/pg_depend.h
   /usr/include/server/catalog/pg_description.h
   /usr/include/server/catalog/pg_enum.h
   /usr/include/server/catalog/pg_event_trigger.h
   /usr/include/server/catalog/pg_extension.h
   /usr/include/server/catalog/pg_foreign_data_wrapper.h
   /usr/include/server/catalog/pg_foreign_server.h
   /usr/include/server/catalog/pg_foreign_table.h
   /usr/include/server/catalog/pg_index.h
   /usr/include/server/catalog/pg_inherits.h
   /usr/include/server/catalog/pg_inherits_fn.h
   /usr/include/server/catalog/pg_init_privs.h
   /usr/include/server/catalog/pg_language.h
   /usr/include/server/catalog/pg_largeobject.h
   /usr/include/server/catalog/pg_largeobject_metadata.h
   /usr/include/server/catalog/pg_namespace.h
   /usr/include/server/catalog/pg_opclass.h
   /usr/include/server/catalog/pg_operator.h
   /usr/include/server/catalog/pg_operator_fn.h
   /usr/include/server/catalog/pg_opfamily.h
   /usr/include/server/catalog/pg_pltemplate.h
   /usr/include/server/catalog/pg_policy.h
   /usr/include/server/catalog/pg_proc.h
   /usr/include/server/catalog/pg_proc_fn.h
   /usr/include/server/catalog/pg_range.h
   /usr/include/server/catalog/pg_replication_origin.h
   /usr/include/server/catalog/pg_rewrite.h
   /usr/include/server/catalog/pg_seclabel.h
   /usr/include/server/catalog/pg_shdepend.h
   /usr/include/server/catalog/pg_shdescription.h
   /usr/include/server/catalog/pg_shseclabel.h
   /usr/include/server/catalog/pg_statistic.h
   /usr/include/server/catalog/pg_tablespace.h
   /usr/include/server/catalog/pg_transform.h
   /usr/include/server/catalog/pg_trigger.h
   /usr/include/server/catalog/pg_ts_config.h
   /usr/include/server/catalog/pg_ts_config_map.h
   /usr/include/server/catalog/pg_ts_dict.h
   /usr/include/server/catalog/pg_ts_parser.h
   /usr/include/server/catalog/pg_ts_template.h
   /usr/include/server/catalog/pg_type.h
   /usr/include/server/catalog/pg_type_fn.h
   /usr/include/server/catalog/pg_user_mapping.h
   /usr/include/server/catalog/schemapg.h
   /usr/include/server/catalog/storage.h
   /usr/include/server/catalog/storage_xlog.h
   /usr/include/server/catalog/toasting.h
   /usr/include/server/commands/alter.h
   /usr/include/server/commands/async.h
   /usr/include/server/commands/cluster.h
   /usr/include/server/commands/collationcmds.h
   /usr/include/server/commands/comment.h
   /usr/include/server/commands/conversioncmds.h
   /usr/include/server/commands/copy.h
   /usr/include/server/commands/createas.h
   /usr/include/server/commands/dbcommands.h
   /usr/include/server/commands/dbcommands_xlog.h
   /usr/include/server/commands/defrem.h
   /usr/include/server/commands/discard.h
   /usr/include/server/commands/event_trigger.h
   /usr/include/server/commands/explain.h
   /usr/include/server/commands/extension.h
   /usr/include/server/commands/lockcmds.h
   /usr/include/server/commands/matview.h
   /usr/include/server/commands/policy.h
   /usr/include/server/commands/portalcmds.h
   /usr/include/server/commands/prepare.h
   /usr/include/server/commands/proclang.h
   /usr/include/server/commands/progress.h
   /usr/include/server/commands/schemacmds.h
   /usr/include/server/commands/seclabel.h
   /usr/include/server/commands/sequence.h
   /usr/include/server/commands/tablecmds.h
   /usr/include/server/commands/tablespace.h
   /usr/include/server/commands/trigger.h
   /usr/include/server/commands/typecmds.h
   /usr/include/server/commands/user.h
   /usr/include/server/commands/vacuum.h
   /usr/include/server/commands/variable.h
   /usr/include/server/commands/view.h
   /usr/include/server/common/config_info.h
   /usr/include/server/common/controldata_utils.h
   /usr/include/server/common/fe_memutils.h
   /usr/include/server/common/int128.h
   /usr/include/server/common/keywords.h
   /usr/include/server/common/pg_lzcompress.h
   /usr/include/server/common/relpath.h
   /usr/include/server/common/restricted_token.h
   /usr/include/server/common/string.h
   /usr/include/server/common/username.h
   /usr/include/server/datatype/timestamp.h
   /usr/include/server/dynloader.h
   /usr/include/server/executor/execParallel.h
   /usr/include/server/executor/execdebug.h
   /usr/include/server/executor/execdesc.h
   /usr/include/server/executor/executor.h
   /usr/include/server/executor/functions.h
   /usr/include/server/executor/hashjoin.h
   /usr/include/server/executor/instrument.h
   /usr/include/server/executor/nodeAgg.h
   /usr/include/server/executor/nodeAppend.h
   /usr/include/server/executor/nodeBitmapAnd.h
   /usr/include/server/executor/nodeBitmapHeapscan.h
   /usr/include/server/executor/nodeBitmapIndexscan.h
   /usr/include/server/executor/nodeBitmapOr.h
   /usr/include/server/executor/nodeCtescan.h
   /usr/include/server/executor/nodeCustom.h
   /usr/include/server/executor/nodeForeignscan.h
   /usr/include/server/executor/nodeFunctionscan.h
   /usr/include/server/executor/nodeGather.h
   /usr/include/server/executor/nodeGroup.h
   /usr/include/server/executor/nodeHash.h
   /usr/include/server/executor/nodeHashjoin.h
   /usr/include/server/executor/nodeIndexonlyscan.h
   /usr/include/server/executor/nodeIndexscan.h
   /usr/include/server/executor/nodeLimit.h
   /usr/include/server/executor/nodeLockRows.h
   /usr/include/server/executor/nodeMaterial.h
   /usr/include/server/executor/nodeMergeAppend.h
   /usr/include/server/executor/nodeMergejoin.h
   /usr/include/server/executor/nodeModifyTable.h
   /usr/include/server/executor/nodeNestloop.h
   /usr/include/server/executor/nodeRecursiveunion.h
   /usr/include/server/executor/nodeResult.h
   /usr/include/server/executor/nodeSamplescan.h
   /usr/include/server/executor/nodeSeqscan.h
   /usr/include/server/executor/nodeSetOp.h
   /usr/include/server/executor/nodeSort.h
   /usr/include/server/executor/nodeSubplan.h
   /usr/include/server/executor/nodeSubqueryscan.h
   /usr/include/server/executor/nodeTidscan.h
   /usr/include/server/executor/nodeUnique.h
   /usr/include/server/executor/nodeValuesscan.h
   /usr/include/server/executor/nodeWindowAgg.h
   /usr/include/server/executor/nodeWorktablescan.h
   /usr/include/server/executor/spi.h
   /usr/include/server/executor/spi_priv.h
   /usr/include/server/executor/tqueue.h
   /usr/include/server/executor/tstoreReceiver.h
   /usr/include/server/executor/tuptable.h
   /usr/include/server/fe_utils/mbprint.h
   /usr/include/server/fe_utils/print.h
   /usr/include/server/fe_utils/psqlscan.h
   /usr/include/server/fe_utils/psqlscan_int.h
   /usr/include/server/fe_utils/simple_list.h
   /usr/include/server/fe_utils/string_utils.h
   /usr/include/server/fmgr.h
   /usr/include/server/foreign/fdwapi.h
   /usr/include/server/foreign/foreign.h
   /usr/include/server/funcapi.h
   /usr/include/server/getaddrinfo.h
   /usr/include/server/getopt_long.h
   /usr/include/server/lib/binaryheap.h
   /usr/include/server/lib/bipartite_match.h
   /usr/include/server/lib/hyperloglog.h
   /usr/include/server/lib/ilist.h
   /usr/include/server/lib/pairingheap.h
   /usr/include/server/lib/rbtree.h
   /usr/include/server/lib/stringinfo.h
   /usr/include/server/libpq/auth.h
   /usr/include/server/libpq/be-fsstubs.h
   /usr/include/server/libpq/crypt.h
   /usr/include/server/libpq/hba.h
   /usr/include/server/libpq/ip.h
   /usr/include/server/libpq/libpq-be.h
   /usr/include/server/libpq/libpq-fs.h
   /usr/include/server/libpq/libpq.h
   /usr/include/server/libpq/md5.h
   /usr/include/server/libpq/pqcomm.h
   /usr/include/server/libpq/pqformat.h
   /usr/include/server/libpq/pqmq.h
   /usr/include/server/libpq/pqsignal.h
   /usr/include/server/mb/pg_wchar.h
   /usr/include/server/miscadmin.h
   /usr/include/server/nodes/bitmapset.h
   /usr/include/server/nodes/execnodes.h
   /usr/include/server/nodes/extensible.h
   /usr/include/server/nodes/lockoptions.h
   /usr/include/server/nodes/makefuncs.h
   /usr/include/server/nodes/memnodes.h
   /usr/include/server/nodes/nodeFuncs.h
   /usr/include/server/nodes/nodes.h
   /usr/include/server/nodes/params.h
   /usr/include/server/nodes/parsenodes.h
   /usr/include/server/nodes/pg_list.h
   /usr/include/server/nodes/plannodes.h
   /usr/include/server/nodes/primnodes.h
   /usr/include/server/nodes/print.h
   /usr/include/server/nodes/readfuncs.h
   /usr/include/server/nodes/relation.h
   /usr/include/server/nodes/replnodes.h
   /usr/include/server/nodes/tidbitmap.h
   /usr/include/server/nodes/value.h
   /usr/include/server/optimizer/clauses.h
   /usr/include/server/optimizer/cost.h
   /usr/include/server/optimizer/geqo.h
   /usr/include/server/optimizer/geqo_copy.h
   /usr/include/server/optimizer/geqo_gene.h
   /usr/include/server/optimizer/geqo_misc.h
   /usr/include/server/optimizer/geqo_mutation.h
   /usr/include/server/optimizer/geqo_pool.h
   /usr/include/server/optimizer/geqo_random.h
   /usr/include/server/optimizer/geqo_recombination.h
   /usr/include/server/optimizer/geqo_selection.h
   /usr/include/server/optimizer/joininfo.h
   /usr/include/server/optimizer/orclauses.h
   /usr/include/server/optimizer/pathnode.h
   /usr/include/server/optimizer/paths.h
   /usr/include/server/optimizer/placeholder.h
   /usr/include/server/optimizer/plancat.h
   /usr/include/server/optimizer/planmain.h
   /usr/include/server/optimizer/planner.h
   /usr/include/server/optimizer/predtest.h
   /usr/include/server/optimizer/prep.h
   /usr/include/server/optimizer/restrictinfo.h
   /usr/include/server/optimizer/subselect.h
   /usr/include/server/optimizer/tlist.h
   /usr/include/server/optimizer/var.h
   /usr/include/server/parser/analyze.h
   /usr/include/server/parser/gram.h
   /usr/include/server/parser/gramparse.h
   /usr/include/server/parser/kwlist.h
   /usr/include/server/parser/parse_agg.h
   /usr/include/server/parser/parse_clause.h
   /usr/include/server/parser/parse_coerce.h
   /usr/include/server/parser/parse_collate.h
   /usr/include/server/parser/parse_cte.h
   /usr/include/server/parser/parse_expr.h
   /usr/include/server/parser/parse_func.h
   /usr/include/server/parser/parse_node.h
   /usr/include/server/parser/parse_oper.h
   /usr/include/server/parser/parse_param.h
   /usr/include/server/parser/parse_relation.h
   /usr/include/server/parser/parse_target.h
   /usr/include/server/parser/parse_type.h
   /usr/include/server/parser/parse_utilcmd.h
   /usr/include/server/parser/parser.h
   /usr/include/server/parser/parsetree.h
   /usr/include/server/parser/scanner.h
   /usr/include/server/parser/scansup.h
   /usr/include/server/pg_config.h
   /usr/include/server/pg_config_ext.h
   /usr/include/server/pg_config_manual.h
   /usr/include/server/pg_config_os.h
   /usr/include/server/pg_getopt.h
   /usr/include/server/pg_trace.h
   /usr/include/server/pgstat.h
   /usr/include/server/pgtar.h
   /usr/include/server/pgtime.h
   /usr/include/server/plpgsql.h
   /usr/include/server/port.h
   /usr/include/server/port/aix.h
   /usr/include/server/port/atomics.h
   /usr/include/server/port/atomics/arch-arm.h
   /usr/include/server/port/atomics/arch-hppa.h
   /usr/include/server/port/atomics/arch-ia64.h
   /usr/include/server/port/atomics/arch-ppc.h
   /usr/include/server/port/atomics/arch-x86.h
   /usr/include/server/port/atomics/fallback.h
   /usr/include/server/port/atomics/generic-acc.h
   /usr/include/server/port/atomics/generic-gcc.h
   /usr/include/server/port/atomics/generic-msvc.h
   /usr/include/server/port/atomics/generic-sunpro.h
   /usr/include/server/port/atomics/generic-xlc.h
   /usr/include/server/port/atomics/generic.h
   /usr/include/server/port/cygwin.h
   /usr/include/server/port/darwin.h
   /usr/include/server/port/freebsd.h
   /usr/include/server/port/hpux.h
   /usr/include/server/port/linux.h
   /usr/include/server/port/netbsd.h
   /usr/include/server/port/openbsd.h
   /usr/include/server/port/pg_bswap.h
   /usr/include/server/port/pg_crc32c.h
   /usr/include/server/port/sco.h
   /usr/include/server/port/solaris.h
   /usr/include/server/port/unixware.h
   /usr/include/server/port/win32.h
   /usr/include/server/port/win32/arpa/inet.h
   /usr/include/server/port/win32/dlfcn.h
   /usr/include/server/port/win32/grp.h
   /usr/include/server/port/win32/netdb.h
   /usr/include/server/port/win32/netinet/in.h
   /usr/include/server/port/win32/pwd.h
   /usr/include/server/port/win32/sys/socket.h
   /usr/include/server/port/win32/sys/wait.h
   /usr/include/server/port/win32_msvc/dirent.h
   /usr/include/server/port/win32_msvc/sys/file.h
   /usr/include/server/port/win32_msvc/sys/param.h
   /usr/include/server/port/win32_msvc/sys/time.h
   /usr/include/server/port/win32_msvc/unistd.h
   /usr/include/server/port/win32_msvc/utime.h
   /usr/include/server/portability/instr_time.h
   /usr/include/server/portability/mem.h
   /usr/include/server/postgres.h
   /usr/include/server/postgres_ext.h
   /usr/include/server/postgres_fe.h
   /usr/include/server/postmaster/autovacuum.h
   /usr/include/server/postmaster/bgworker.h
   /usr/include/server/postmaster/bgworker_internals.h
   /usr/include/server/postmaster/bgwriter.h
   /usr/include/server/postmaster/fork_process.h
   /usr/include/server/postmaster/pgarch.h
   /usr/include/server/postmaster/postmaster.h
   /usr/include/server/postmaster/startup.h
   /usr/include/server/postmaster/syslogger.h
   /usr/include/server/postmaster/walwriter.h
   /usr/include/server/regex/regcustom.h
   /usr/include/server/regex/regerrs.h
   /usr/include/server/regex/regex.h
   /usr/include/server/regex/regexport.h
   /usr/include/server/regex/regguts.h
   /usr/include/server/replication/basebackup.h
   /usr/include/server/replication/decode.h
   /usr/include/server/replication/logical.h
   /usr/include/server/replication/logicalfuncs.h
   /usr/include/server/replication/message.h
   /usr/include/server/replication/origin.h
   /usr/include/server/replication/output_plugin.h
   /usr/include/server/replication/reorderbuffer.h
   /usr/include/server/replication/slot.h
   /usr/include/server/replication/snapbuild.h
   /usr/include/server/replication/syncrep.h
   /usr/include/server/replication/walreceiver.h
   /usr/include/server/replication/walsender.h
   /usr/include/server/replication/walsender_private.h
   /usr/include/server/rewrite/prs2lock.h
   /usr/include/server/rewrite/rewriteDefine.h
   /usr/include/server/rewrite/rewriteHandler.h
   /usr/include/server/rewrite/rewriteManip.h
   /usr/include/server/rewrite/rewriteRemove.h
   /usr/include/server/rewrite/rewriteSupport.h
   /usr/include/server/rewrite/rowsecurity.h
   /usr/include/server/rusagestub.h
   /usr/include/server/snowball/header.h
   /usr/include/server/snowball/libstemmer/api.h
   /usr/include/server/snowball/libstemmer/header.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_danish.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_dutch.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_english.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_finnish.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_french.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_german.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_hungarian.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_italian.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_norwegian.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_porter.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_portuguese.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_spanish.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_1_swedish.h
   /usr/include/server/snowball/libstemmer/stem_ISO_8859_2_romanian.h
   /usr/include/server/snowball/libstemmer/stem_KOI8_R_russian.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_danish.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_dutch.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_english.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_finnish.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_french.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_german.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_hungarian.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_italian.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_norwegian.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_porter.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_portuguese.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_romanian.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_russian.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_spanish.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_swedish.h
   /usr/include/server/snowball/libstemmer/stem_UTF_8_turkish.h
   /usr/include/server/storage/backendid.h
   /usr/include/server/storage/barrier.h
   /usr/include/server/storage/block.h
   /usr/include/server/storage/buf.h
   /usr/include/server/storage/buf_internals.h
   /usr/include/server/storage/buffile.h
   /usr/include/server/storage/bufmgr.h
   /usr/include/server/storage/bufpage.h
   /usr/include/server/storage/checksum.h
   /usr/include/server/storage/checksum_impl.h
   /usr/include/server/storage/copydir.h
   /usr/include/server/storage/dsm.h
   /usr/include/server/storage/dsm_impl.h
   /usr/include/server/storage/fd.h
   /usr/include/server/storage/freespace.h
   /usr/include/server/storage/fsm_internals.h
   /usr/include/server/storage/indexfsm.h
   /usr/include/server/storage/ipc.h
   /usr/include/server/storage/item.h
   /usr/include/server/storage/itemid.h
   /usr/include/server/storage/itemptr.h
   /usr/include/server/storage/large_object.h
   /usr/include/server/storage/latch.h
   /usr/include/server/storage/lmgr.h
   /usr/include/server/storage/lock.h
   /usr/include/server/storage/lockdefs.h
   /usr/include/server/storage/lwlock.h
   /usr/include/server/storage/lwlocknames.h
   /usr/include/server/storage/off.h
   /usr/include/server/storage/pg_sema.h
   /usr/include/server/storage/pg_shmem.h
   /usr/include/server/storage/pmsignal.h
   /usr/include/server/storage/pos.h
   /usr/include/server/storage/predicate.h
   /usr/include/server/storage/predicate_internals.h
   /usr/include/server/storage/proc.h
   /usr/include/server/storage/procarray.h
   /usr/include/server/storage/procsignal.h
   /usr/include/server/storage/reinit.h
   /usr/include/server/storage/relfilenode.h
   /usr/include/server/storage/s_lock.h
   /usr/include/server/storage/shm_mq.h
   /usr/include/server/storage/shm_toc.h
   /usr/include/server/storage/shmem.h
   /usr/include/server/storage/sinval.h
   /usr/include/server/storage/sinvaladt.h
   /usr/include/server/storage/smgr.h
   /usr/include/server/storage/spin.h
   /usr/include/server/storage/standby.h
   /usr/include/server/storage/standbydefs.h
   /usr/include/server/tcop/deparse_utility.h
   /usr/include/server/tcop/dest.h
   /usr/include/server/tcop/fastpath.h
   /usr/include/server/tcop/pquery.h
   /usr/include/server/tcop/tcopprot.h
   /usr/include/server/tcop/utility.h
   /usr/include/server/tsearch/dicts/regis.h
   /usr/include/server/tsearch/dicts/spell.h
   /usr/include/server/tsearch/ts_cache.h
   /usr/include/server/tsearch/ts_locale.h
   /usr/include/server/tsearch/ts_public.h
   /usr/include/server/tsearch/ts_type.h
   /usr/include/server/tsearch/ts_utils.h
   /usr/include/server/utils/acl.h
   /usr/include/server/utils/aclchk_internal.h
   /usr/include/server/utils/array.h
   /usr/include/server/utils/arrayaccess.h
   /usr/include/server/utils/ascii.h
   /usr/include/server/utils/attoptcache.h
   /usr/include/server/utils/builtins.h
   /usr/include/server/utils/bytea.h
   /usr/include/server/utils/cash.h
   /usr/include/server/utils/catcache.h
   /usr/include/server/utils/combocid.h
   /usr/include/server/utils/date.h
   /usr/include/server/utils/datetime.h
   /usr/include/server/utils/datum.h
   /usr/include/server/utils/dynahash.h
   /usr/include/server/utils/dynamic_loader.h
   /usr/include/server/utils/elog.h
   /usr/include/server/utils/errcodes.h
   /usr/include/server/utils/evtcache.h
   /usr/include/server/utils/expandeddatum.h
   /usr/include/server/utils/fmgroids.h
   /usr/include/server/utils/fmgrtab.h
   /usr/include/server/utils/formatting.h
   /usr/include/server/utils/geo_decls.h
   /usr/include/server/utils/guc.h
   /usr/include/server/utils/guc_tables.h
   /usr/include/server/utils/help_config.h
   /usr/include/server/utils/hsearch.h
   /usr/include/server/utils/index_selfuncs.h
   /usr/include/server/utils/inet.h
   /usr/include/server/utils/int8.h
   /usr/include/server/utils/inval.h
   /usr/include/server/utils/json.h
   /usr/include/server/utils/jsonapi.h
   /usr/include/server/utils/jsonb.h
   /usr/include/server/utils/logtape.h
   /usr/include/server/utils/lsyscache.h
   /usr/include/server/utils/memdebug.h
   /usr/include/server/utils/memutils.h
   /usr/include/server/utils/nabstime.h
   /usr/include/server/utils/numeric.h
   /usr/include/server/utils/palloc.h
   /usr/include/server/utils/pg_crc.h
   /usr/include/server/utils/pg_locale.h
   /usr/include/server/utils/pg_lsn.h
   /usr/include/server/utils/pg_rusage.h
   /usr/include/server/utils/plancache.h
   /usr/include/server/utils/portal.h
   /usr/include/server/utils/probes.h
   /usr/include/server/utils/ps_status.h
   /usr/include/server/utils/rangetypes.h
   /usr/include/server/utils/rel.h
   /usr/include/server/utils/relcache.h
   /usr/include/server/utils/relfilenodemap.h
   /usr/include/server/utils/relmapper.h
   /usr/include/server/utils/reltrigger.h
   /usr/include/server/utils/resowner.h
   /usr/include/server/utils/resowner_private.h
   /usr/include/server/utils/rls.h
   /usr/include/server/utils/ruleutils.h
   /usr/include/server/utils/sampling.h
   /usr/include/server/utils/selfuncs.h
   /usr/include/server/utils/snapmgr.h
   /usr/include/server/utils/snapshot.h
   /usr/include/server/utils/sortsupport.h
   /usr/include/server/utils/spccache.h
   /usr/include/server/utils/syscache.h
   /usr/include/server/utils/timeout.h
   /usr/include/server/utils/timestamp.h
   /usr/include/server/utils/tqual.h
   /usr/include/server/utils/tuplesort.h
   /usr/include/server/utils/tuplestore.h
   /usr/include/server/utils/typcache.h
   /usr/include/server/utils/tzparser.h
   /usr/include/server/utils/uuid.h
   /usr/include/server/utils/varbit.h
   /usr/include/server/utils/xml.h
   /usr/include/server/windowapi.h
   /usr/include/sql3types.h
   /usr/include/sqlca.h
   /usr/include/sqlda-compat.h
   /usr/include/sqlda-native.h
   /usr/include/sqlda.h
   /usr/lib64/ascii_and_mic.so
   /usr/lib64/cyrillic_and_mic.so
   /usr/lib64/dict_snowball.so
   /usr/lib64/euc2004_sjis2004.so
   /usr/lib64/euc_cn_and_mic.so
   /usr/lib64/euc_jp_and_sjis.so
   /usr/lib64/euc_kr_and_mic.so
   /usr/lib64/euc_tw_and_big5.so
   /usr/lib64/latin2_and_win1250.so
   /usr/lib64/latin_and_mic.so
   /usr/lib64/libecpg.a
   /usr/lib64/libecpg.so
   /usr/lib64/libecpg.so.6
   /usr/lib64/libecpg.so.6.8
   /usr/lib64/libecpg_compat.a
   /usr/lib64/libecpg_compat.so
   /usr/lib64/libecpg_compat.so.3
   /usr/lib64/libecpg_compat.so.3.8
   /usr/lib64/libpgcommon.a
   /usr/lib64/libpgfeutils.a
   /usr/lib64/libpgport.a
   /usr/lib64/libpgtypes.a
   /usr/lib64/libpgtypes.so
   /usr/lib64/libpgtypes.so.3
   /usr/lib64/libpgtypes.so.3.7
   /usr/lib64/libpq.a
   /usr/lib64/libpq.so
   /usr/lib64/libpq.so.5
   /usr/lib64/libpq.so.5.9
   /usr/lib64/libpqwalreceiver.so
   /usr/lib64/pgxs/config/install-sh
   /usr/lib64/pgxs/config/missing
   /usr/lib64/pgxs/src/Makefile.global
   /usr/lib64/pgxs/src/Makefile.port
   /usr/lib64/pgxs/src/Makefile.shlib
   /usr/lib64/pgxs/src/makefiles/pgxs.mk
   /usr/lib64/pgxs/src/nls-global.mk
   /usr/lib64/pgxs/src/test/regress/pg_regress
   /usr/lib64/pkgconfig/libecpg.pc
   /usr/lib64/pkgconfig/libecpg_compat.pc
   /usr/lib64/pkgconfig/libpgtypes.pc
   /usr/lib64/pkgconfig/libpq.pc
   /usr/lib64/plpgsql.so
   /usr/lib64/utf8_and_ascii.so
   /usr/lib64/utf8_and_big5.so
   /usr/lib64/utf8_and_cyrillic.so
   /usr/lib64/utf8_and_euc2004.so
   /usr/lib64/utf8_and_euc_cn.so
   /usr/lib64/utf8_and_euc_jp.so
   /usr/lib64/utf8_and_euc_kr.so
   /usr/lib64/utf8_and_euc_tw.so
   /usr/lib64/utf8_and_gb18030.so
   /usr/lib64/utf8_and_gbk.so
   /usr/lib64/utf8_and_iso8859.so
   /usr/lib64/utf8_and_iso8859_1.so
   /usr/lib64/utf8_and_johab.so
   /usr/lib64/utf8_and_sjis.so
   /usr/lib64/utf8_and_sjis2004.so
   /usr/lib64/utf8_and_uhc.so
   /usr/lib64/utf8_and_win.so
   /usr/share/conversion_create.sql
   /usr/share/extension/plpgsql--1.0.sql
   /usr/share/extension/plpgsql--unpackaged--1.0.sql
   /usr/share/extension/plpgsql.control
   /usr/share/information_schema.sql
   /usr/share/pg_hba.conf.sample
   /usr/share/pg_ident.conf.sample
   /usr/share/pg_service.conf.sample
   /usr/share/postgres.bki
   /usr/share/postgres.description
   /usr/share/postgres.shdescription
   /usr/share/postgresql.conf.sample
   /usr/share/psqlrc.sample
   /usr/share/recovery.conf.sample
   /usr/share/snowball_create.sql
   /usr/share/sql_features.txt
   /usr/share/system_views.sql
   /usr/share/timezone/Africa/Abidjan
   /usr/share/timezone/Africa/Accra
   /usr/share/timezone/Africa/Addis_Ababa
   /usr/share/timezone/Africa/Algiers
   /usr/share/timezone/Africa/Asmara
   /usr/share/timezone/Africa/Asmera
   /usr/share/timezone/Africa/Bamako
   /usr/share/timezone/Africa/Bangui
   /usr/share/timezone/Africa/Banjul
   /usr/share/timezone/Africa/Bissau
   /usr/share/timezone/Africa/Blantyre
   /usr/share/timezone/Africa/Brazzaville
   /usr/share/timezone/Africa/Bujumbura
   /usr/share/timezone/Africa/Cairo
   /usr/share/timezone/Africa/Casablanca
   /usr/share/timezone/Africa/Ceuta
   /usr/share/timezone/Africa/Conakry
   /usr/share/timezone/Africa/Dakar
   /usr/share/timezone/Africa/Dar_es_Salaam
   /usr/share/timezone/Africa/Djibouti
   /usr/share/timezone/Africa/Douala
   /usr/share/timezone/Africa/El_Aaiun
   /usr/share/timezone/Africa/Freetown
   /usr/share/timezone/Africa/Gaborone
   /usr/share/timezone/Africa/Harare
   /usr/share/timezone/Africa/Johannesburg
   /usr/share/timezone/Africa/Juba
   /usr/share/timezone/Africa/Kampala
   /usr/share/timezone/Africa/Khartoum
   /usr/share/timezone/Africa/Kigali
   /usr/share/timezone/Africa/Kinshasa
   /usr/share/timezone/Africa/Lagos
   /usr/share/timezone/Africa/Libreville
   /usr/share/timezone/Africa/Lome
   /usr/share/timezone/Africa/Luanda
   /usr/share/timezone/Africa/Lubumbashi
   /usr/share/timezone/Africa/Lusaka
   /usr/share/timezone/Africa/Malabo
   /usr/share/timezone/Africa/Maputo
   /usr/share/timezone/Africa/Maseru
   /usr/share/timezone/Africa/Mbabane
   /usr/share/timezone/Africa/Mogadishu
   /usr/share/timezone/Africa/Monrovia
   /usr/share/timezone/Africa/Nairobi
   /usr/share/timezone/Africa/Ndjamena
   /usr/share/timezone/Africa/Niamey
   /usr/share/timezone/Africa/Nouakchott
   /usr/share/timezone/Africa/Ouagadougou
   /usr/share/timezone/Africa/Porto-Novo
   /usr/share/timezone/Africa/Sao_Tome
   /usr/share/timezone/Africa/Timbuktu
   /usr/share/timezone/Africa/Tripoli
   /usr/share/timezone/Africa/Tunis
   /usr/share/timezone/Africa/Windhoek
   /usr/share/timezone/America/Adak
   /usr/share/timezone/America/Anchorage
   /usr/share/timezone/America/Anguilla
   /usr/share/timezone/America/Antigua
   /usr/share/timezone/America/Araguaina
   /usr/share/timezone/America/Argentina/Buenos_Aires
   /usr/share/timezone/America/Argentina/Catamarca
   /usr/share/timezone/America/Argentina/ComodRivadavia
   /usr/share/timezone/America/Argentina/Cordoba
   /usr/share/timezone/America/Argentina/Jujuy
   /usr/share/timezone/America/Argentina/La_Rioja
   /usr/share/timezone/America/Argentina/Mendoza
   /usr/share/timezone/America/Argentina/Rio_Gallegos
   /usr/share/timezone/America/Argentina/Salta
   /usr/share/timezone/America/Argentina/San_Juan
   /usr/share/timezone/America/Argentina/San_Luis
   /usr/share/timezone/America/Argentina/Tucuman
   /usr/share/timezone/America/Argentina/Ushuaia
   /usr/share/timezone/America/Aruba
   /usr/share/timezone/America/Asuncion
   /usr/share/timezone/America/Atikokan
   /usr/share/timezone/America/Atka
   /usr/share/timezone/America/Bahia
   /usr/share/timezone/America/Bahia_Banderas
   /usr/share/timezone/America/Barbados
   /usr/share/timezone/America/Belem
   /usr/share/timezone/America/Belize
   /usr/share/timezone/America/Blanc-Sablon
   /usr/share/timezone/America/Boa_Vista
   /usr/share/timezone/America/Bogota
   /usr/share/timezone/America/Boise
   /usr/share/timezone/America/Buenos_Aires
   /usr/share/timezone/America/Cambridge_Bay
   /usr/share/timezone/America/Campo_Grande
   /usr/share/timezone/America/Cancun
   /usr/share/timezone/America/Caracas
   /usr/share/timezone/America/Catamarca
   /usr/share/timezone/America/Cayenne
   /usr/share/timezone/America/Cayman
   /usr/share/timezone/America/Chicago
   /usr/share/timezone/America/Chihuahua
   /usr/share/timezone/America/Coral_Harbour
   /usr/share/timezone/America/Cordoba
   /usr/share/timezone/America/Costa_Rica
   /usr/share/timezone/America/Creston
   /usr/share/timezone/America/Cuiaba
   /usr/share/timezone/America/Curacao
   /usr/share/timezone/America/Danmarkshavn
   /usr/share/timezone/America/Dawson
   /usr/share/timezone/America/Dawson_Creek
   /usr/share/timezone/America/Denver
   /usr/share/timezone/America/Detroit
   /usr/share/timezone/America/Dominica
   /usr/share/timezone/America/Edmonton
   /usr/share/timezone/America/Eirunepe
   /usr/share/timezone/America/El_Salvador
   /usr/share/timezone/America/Ensenada
   /usr/share/timezone/America/Fort_Nelson
   /usr/share/timezone/America/Fort_Wayne
   /usr/share/timezone/America/Fortaleza
   /usr/share/timezone/America/Glace_Bay
   /usr/share/timezone/America/Godthab
   /usr/share/timezone/America/Goose_Bay
   /usr/share/timezone/America/Grand_Turk
   /usr/share/timezone/America/Grenada
   /usr/share/timezone/America/Guadeloupe
   /usr/share/timezone/America/Guatemala
   /usr/share/timezone/America/Guayaquil
   /usr/share/timezone/America/Guyana
   /usr/share/timezone/America/Halifax
   /usr/share/timezone/America/Havana
   /usr/share/timezone/America/Hermosillo
   /usr/share/timezone/America/Indiana/Indianapolis
   /usr/share/timezone/America/Indiana/Knox
   /usr/share/timezone/America/Indiana/Marengo
   /usr/share/timezone/America/Indiana/Petersburg
   /usr/share/timezone/America/Indiana/Tell_City
   /usr/share/timezone/America/Indiana/Vevay
   /usr/share/timezone/America/Indiana/Vincennes
   /usr/share/timezone/America/Indiana/Winamac
   /usr/share/timezone/America/Indianapolis
   /usr/share/timezone/America/Inuvik
   /usr/share/timezone/America/Iqaluit
   /usr/share/timezone/America/Jamaica
   /usr/share/timezone/America/Jujuy
   /usr/share/timezone/America/Juneau
   /usr/share/timezone/America/Kentucky/Louisville
   /usr/share/timezone/America/Kentucky/Monticello
   /usr/share/timezone/America/Knox_IN
   /usr/share/timezone/America/Kralendijk
   /usr/share/timezone/America/La_Paz
   /usr/share/timezone/America/Lima
   /usr/share/timezone/America/Los_Angeles
   /usr/share/timezone/America/Louisville
   /usr/share/timezone/America/Lower_Princes
   /usr/share/timezone/America/Maceio
   /usr/share/timezone/America/Managua
   /usr/share/timezone/America/Manaus
   /usr/share/timezone/America/Marigot
   /usr/share/timezone/America/Martinique
   /usr/share/timezone/America/Matamoros
   /usr/share/timezone/America/Mazatlan
   /usr/share/timezone/America/Mendoza
   /usr/share/timezone/America/Menominee
   /usr/share/timezone/America/Merida
   /usr/share/timezone/America/Metlakatla
   /usr/share/timezone/America/Mexico_City
   /usr/share/timezone/America/Miquelon
   /usr/share/timezone/America/Moncton
   /usr/share/timezone/America/Monterrey
   /usr/share/timezone/America/Montevideo
   /usr/share/timezone/America/Montreal
   /usr/share/timezone/America/Montserrat
   /usr/share/timezone/America/Nassau
   /usr/share/timezone/America/New_York
   /usr/share/timezone/America/Nipigon
   /usr/share/timezone/America/Nome
   /usr/share/timezone/America/Noronha
   /usr/share/timezone/America/North_Dakota/Beulah
   /usr/share/timezone/America/North_Dakota/Center
   /usr/share/timezone/America/North_Dakota/New_Salem
   /usr/share/timezone/America/Ojinaga
   /usr/share/timezone/America/Panama
   /usr/share/timezone/America/Pangnirtung
   /usr/share/timezone/America/Paramaribo
   /usr/share/timezone/America/Phoenix
   /usr/share/timezone/America/Port-au-Prince
   /usr/share/timezone/America/Port_of_Spain
   /usr/share/timezone/America/Porto_Acre
   /usr/share/timezone/America/Porto_Velho
   /usr/share/timezone/America/Puerto_Rico
   /usr/share/timezone/America/Punta_Arenas
   /usr/share/timezone/America/Rainy_River
   /usr/share/timezone/America/Rankin_Inlet
   /usr/share/timezone/America/Recife
   /usr/share/timezone/America/Regina
   /usr/share/timezone/America/Resolute
   /usr/share/timezone/America/Rio_Branco
   /usr/share/timezone/America/Rosario
   /usr/share/timezone/America/Santa_Isabel
   /usr/share/timezone/America/Santarem
   /usr/share/timezone/America/Santiago
   /usr/share/timezone/America/Santo_Domingo
   /usr/share/timezone/America/Sao_Paulo
   /usr/share/timezone/America/Scoresbysund
   /usr/share/timezone/America/Shiprock
   /usr/share/timezone/America/Sitka
   /usr/share/timezone/America/St_Barthelemy
   /usr/share/timezone/America/St_Johns
   /usr/share/timezone/America/St_Kitts
   /usr/share/timezone/America/St_Lucia
   /usr/share/timezone/America/St_Thomas
   /usr/share/timezone/America/St_Vincent
   /usr/share/timezone/America/Swift_Current
   /usr/share/timezone/America/Tegucigalpa
   /usr/share/timezone/America/Thule
   /usr/share/timezone/America/Thunder_Bay
   /usr/share/timezone/America/Tijuana
   /usr/share/timezone/America/Toronto
   /usr/share/timezone/America/Tortola
   /usr/share/timezone/America/Vancouver
   /usr/share/timezone/America/Virgin
   /usr/share/timezone/America/Whitehorse
   /usr/share/timezone/America/Winnipeg
   /usr/share/timezone/America/Yakutat
   /usr/share/timezone/America/Yellowknife
   /usr/share/timezone/Antarctica/Casey
   /usr/share/timezone/Antarctica/Davis
   /usr/share/timezone/Antarctica/DumontDUrville
   /usr/share/timezone/Antarctica/Macquarie
   /usr/share/timezone/Antarctica/Mawson
   /usr/share/timezone/Antarctica/McMurdo
   /usr/share/timezone/Antarctica/Palmer
   /usr/share/timezone/Antarctica/Rothera
   /usr/share/timezone/Antarctica/South_Pole
   /usr/share/timezone/Antarctica/Syowa
   /usr/share/timezone/Antarctica/Troll
   /usr/share/timezone/Antarctica/Vostok
   /usr/share/timezone/Arctic/Longyearbyen
   /usr/share/timezone/Asia/Aden
   /usr/share/timezone/Asia/Almaty
   /usr/share/timezone/Asia/Amman
   /usr/share/timezone/Asia/Anadyr
   /usr/share/timezone/Asia/Aqtau
   /usr/share/timezone/Asia/Aqtobe
   /usr/share/timezone/Asia/Ashgabat
   /usr/share/timezone/Asia/Ashkhabad
   /usr/share/timezone/Asia/Atyrau
   /usr/share/timezone/Asia/Baghdad
   /usr/share/timezone/Asia/Bahrain
   /usr/share/timezone/Asia/Baku
   /usr/share/timezone/Asia/Bangkok
   /usr/share/timezone/Asia/Barnaul
   /usr/share/timezone/Asia/Beirut
   /usr/share/timezone/Asia/Bishkek
   /usr/share/timezone/Asia/Brunei
   /usr/share/timezone/Asia/Calcutta
   /usr/share/timezone/Asia/Chita
   /usr/share/timezone/Asia/Choibalsan
   /usr/share/timezone/Asia/Chongqing
   /usr/share/timezone/Asia/Chungking
   /usr/share/timezone/Asia/Colombo
   /usr/share/timezone/Asia/Dacca
   /usr/share/timezone/Asia/Damascus
   /usr/share/timezone/Asia/Dhaka
   /usr/share/timezone/Asia/Dili
   /usr/share/timezone/Asia/Dubai
   /usr/share/timezone/Asia/Dushanbe
   /usr/share/timezone/Asia/Famagusta
   /usr/share/timezone/Asia/Gaza
   /usr/share/timezone/Asia/Harbin
   /usr/share/timezone/Asia/Hebron
   /usr/share/timezone/Asia/Ho_Chi_Minh
   /usr/share/timezone/Asia/Hong_Kong
   /usr/share/timezone/Asia/Hovd
   /usr/share/timezone/Asia/Irkutsk
   /usr/share/timezone/Asia/Istanbul
   /usr/share/timezone/Asia/Jakarta
   /usr/share/timezone/Asia/Jayapura
   /usr/share/timezone/Asia/Jerusalem
   /usr/share/timezone/Asia/Kabul
   /usr/share/timezone/Asia/Kamchatka
   /usr/share/timezone/Asia/Karachi
   /usr/share/timezone/Asia/Kashgar
   /usr/share/timezone/Asia/Kathmandu
   /usr/share/timezone/Asia/Katmandu
   /usr/share/timezone/Asia/Khandyga
   /usr/share/timezone/Asia/Kolkata
   /usr/share/timezone/Asia/Krasnoyarsk
   /usr/share/timezone/Asia/Kuala_Lumpur
   /usr/share/timezone/Asia/Kuching
   /usr/share/timezone/Asia/Kuwait
   /usr/share/timezone/Asia/Macao
   /usr/share/timezone/Asia/Macau
   /usr/share/timezone/Asia/Magadan
   /usr/share/timezone/Asia/Makassar
   /usr/share/timezone/Asia/Manila
   /usr/share/timezone/Asia/Muscat
   /usr/share/timezone/Asia/Nicosia
   /usr/share/timezone/Asia/Novokuznetsk
   /usr/share/timezone/Asia/Novosibirsk
   /usr/share/timezone/Asia/Omsk
   /usr/share/timezone/Asia/Oral
   /usr/share/timezone/Asia/Phnom_Penh
   /usr/share/timezone/Asia/Pontianak
   /usr/share/timezone/Asia/Pyongyang
   /usr/share/timezone/Asia/Qatar
   /usr/share/timezone/Asia/Qyzylorda
   /usr/share/timezone/Asia/Rangoon
   /usr/share/timezone/Asia/Riyadh
   /usr/share/timezone/Asia/Saigon
   /usr/share/timezone/Asia/Sakhalin
   /usr/share/timezone/Asia/Samarkand
   /usr/share/timezone/Asia/Seoul
   /usr/share/timezone/Asia/Shanghai
   /usr/share/timezone/Asia/Singapore
   /usr/share/timezone/Asia/Srednekolymsk
   /usr/share/timezone/Asia/Taipei
   /usr/share/timezone/Asia/Tashkent
   /usr/share/timezone/Asia/Tbilisi
   /usr/share/timezone/Asia/Tehran
   /usr/share/timezone/Asia/Tel_Aviv
   /usr/share/timezone/Asia/Thimbu
   /usr/share/timezone/Asia/Thimphu
   /usr/share/timezone/Asia/Tokyo
   /usr/share/timezone/Asia/Tomsk
   /usr/share/timezone/Asia/Ujung_Pandang
   /usr/share/timezone/Asia/Ulaanbaatar
   /usr/share/timezone/Asia/Ulan_Bator
   /usr/share/timezone/Asia/Urumqi
   /usr/share/timezone/Asia/Ust-Nera
   /usr/share/timezone/Asia/Vientiane
   /usr/share/timezone/Asia/Vladivostok
   /usr/share/timezone/Asia/Yakutsk
   /usr/share/timezone/Asia/Yangon
   /usr/share/timezone/Asia/Yekaterinburg
   /usr/share/timezone/Asia/Yerevan
   /usr/share/timezone/Atlantic/Azores
   /usr/share/timezone/Atlantic/Bermuda
   /usr/share/timezone/Atlantic/Canary
   /usr/share/timezone/Atlantic/Cape_Verde
   /usr/share/timezone/Atlantic/Faeroe
   /usr/share/timezone/Atlantic/Faroe
   /usr/share/timezone/Atlantic/Jan_Mayen
   /usr/share/timezone/Atlantic/Madeira
   /usr/share/timezone/Atlantic/Reykjavik
   /usr/share/timezone/Atlantic/South_Georgia
   /usr/share/timezone/Atlantic/St_Helena
   /usr/share/timezone/Atlantic/Stanley
   /usr/share/timezone/Australia/ACT
   /usr/share/timezone/Australia/Adelaide
   /usr/share/timezone/Australia/Brisbane
   /usr/share/timezone/Australia/Broken_Hill
   /usr/share/timezone/Australia/Canberra
   /usr/share/timezone/Australia/Currie
   /usr/share/timezone/Australia/Darwin
   /usr/share/timezone/Australia/Eucla
   /usr/share/timezone/Australia/Hobart
   /usr/share/timezone/Australia/LHI
   /usr/share/timezone/Australia/Lindeman
   /usr/share/timezone/Australia/Lord_Howe
   /usr/share/timezone/Australia/Melbourne
   /usr/share/timezone/Australia/NSW
   /usr/share/timezone/Australia/North
   /usr/share/timezone/Australia/Perth
   /usr/share/timezone/Australia/Queensland
   /usr/share/timezone/Australia/South
   /usr/share/timezone/Australia/Sydney
   /usr/share/timezone/Australia/Tasmania
   /usr/share/timezone/Australia/Victoria
   /usr/share/timezone/Australia/West
   /usr/share/timezone/Australia/Yancowinna
   /usr/share/timezone/Brazil/Acre
   /usr/share/timezone/Brazil/DeNoronha
   /usr/share/timezone/Brazil/East
   /usr/share/timezone/Brazil/West
   /usr/share/timezone/CET
   /usr/share/timezone/CST6CDT
   /usr/share/timezone/Canada/Atlantic
   /usr/share/timezone/Canada/Central
   /usr/share/timezone/Canada/East-Saskatchewan
   /usr/share/timezone/Canada/Eastern
   /usr/share/timezone/Canada/Mountain
   /usr/share/timezone/Canada/Newfoundland
   /usr/share/timezone/Canada/Pacific
   /usr/share/timezone/Canada/Saskatchewan
   /usr/share/timezone/Canada/Yukon
   /usr/share/timezone/Chile/Continental
   /usr/share/timezone/Chile/EasterIsland
   /usr/share/timezone/Cuba
   /usr/share/timezone/EET
   /usr/share/timezone/EST
   /usr/share/timezone/EST5EDT
   /usr/share/timezone/Egypt
   /usr/share/timezone/Eire
   /usr/share/timezone/Etc/GMT
   /usr/share/timezone/Etc/GMT+0
   /usr/share/timezone/Etc/GMT+1
   /usr/share/timezone/Etc/GMT+10
   /usr/share/timezone/Etc/GMT+11
   /usr/share/timezone/Etc/GMT+12
   /usr/share/timezone/Etc/GMT+2
   /usr/share/timezone/Etc/GMT+3
   /usr/share/timezone/Etc/GMT+4
   /usr/share/timezone/Etc/GMT+5
   /usr/share/timezone/Etc/GMT+6
   /usr/share/timezone/Etc/GMT+7
   /usr/share/timezone/Etc/GMT+8
   /usr/share/timezone/Etc/GMT+9
   /usr/share/timezone/Etc/GMT-0
   /usr/share/timezone/Etc/GMT-1
   /usr/share/timezone/Etc/GMT-10
   /usr/share/timezone/Etc/GMT-11
   /usr/share/timezone/Etc/GMT-12
   /usr/share/timezone/Etc/GMT-13
   /usr/share/timezone/Etc/GMT-14
   /usr/share/timezone/Etc/GMT-2
   /usr/share/timezone/Etc/GMT-3
   /usr/share/timezone/Etc/GMT-4
   /usr/share/timezone/Etc/GMT-5
   /usr/share/timezone/Etc/GMT-6
   /usr/share/timezone/Etc/GMT-7
   /usr/share/timezone/Etc/GMT-8
   /usr/share/timezone/Etc/GMT-9
   /usr/share/timezone/Etc/GMT0
   /usr/share/timezone/Etc/Greenwich
   /usr/share/timezone/Etc/UCT
   /usr/share/timezone/Etc/UTC
   /usr/share/timezone/Etc/Universal
   /usr/share/timezone/Etc/Zulu
   /usr/share/timezone/Europe/Amsterdam
   /usr/share/timezone/Europe/Andorra
   /usr/share/timezone/Europe/Astrakhan
   /usr/share/timezone/Europe/Athens
   /usr/share/timezone/Europe/Belfast
   /usr/share/timezone/Europe/Belgrade
   /usr/share/timezone/Europe/Berlin
   /usr/share/timezone/Europe/Bratislava
   /usr/share/timezone/Europe/Brussels
   /usr/share/timezone/Europe/Bucharest
   /usr/share/timezone/Europe/Budapest
   /usr/share/timezone/Europe/Busingen
   /usr/share/timezone/Europe/Chisinau
   /usr/share/timezone/Europe/Copenhagen
   /usr/share/timezone/Europe/Dublin
   /usr/share/timezone/Europe/Gibraltar
   /usr/share/timezone/Europe/Guernsey
   /usr/share/timezone/Europe/Helsinki
   /usr/share/timezone/Europe/Isle_of_Man
   /usr/share/timezone/Europe/Istanbul
   /usr/share/timezone/Europe/Jersey
   /usr/share/timezone/Europe/Kaliningrad
   /usr/share/timezone/Europe/Kiev
   /usr/share/timezone/Europe/Kirov
   /usr/share/timezone/Europe/Lisbon
   /usr/share/timezone/Europe/Ljubljana
   /usr/share/timezone/Europe/London
   /usr/share/timezone/Europe/Luxembourg
   /usr/share/timezone/Europe/Madrid
   /usr/share/timezone/Europe/Malta
   /usr/share/timezone/Europe/Mariehamn
   /usr/share/timezone/Europe/Minsk
   /usr/share/timezone/Europe/Monaco
   /usr/share/timezone/Europe/Moscow
   /usr/share/timezone/Europe/Nicosia
   /usr/share/timezone/Europe/Oslo
   /usr/share/timezone/Europe/Paris
   /usr/share/timezone/Europe/Podgorica
   /usr/share/timezone/Europe/Prague
   /usr/share/timezone/Europe/Riga
   /usr/share/timezone/Europe/Rome
   /usr/share/timezone/Europe/Samara
   /usr/share/timezone/Europe/San_Marino
   /usr/share/timezone/Europe/Sarajevo
   /usr/share/timezone/Europe/Saratov
   /usr/share/timezone/Europe/Simferopol
   /usr/share/timezone/Europe/Skopje
   /usr/share/timezone/Europe/Sofia
   /usr/share/timezone/Europe/Stockholm
   /usr/share/timezone/Europe/Tallinn
   /usr/share/timezone/Europe/Tirane
   /usr/share/timezone/Europe/Tiraspol
   /usr/share/timezone/Europe/Ulyanovsk
   /usr/share/timezone/Europe/Uzhgorod
   /usr/share/timezone/Europe/Vaduz
   /usr/share/timezone/Europe/Vatican
   /usr/share/timezone/Europe/Vienna
   /usr/share/timezone/Europe/Vilnius
   /usr/share/timezone/Europe/Volgograd
   /usr/share/timezone/Europe/Warsaw
   /usr/share/timezone/Europe/Zagreb
   /usr/share/timezone/Europe/Zaporozhye
   /usr/share/timezone/Europe/Zurich
   /usr/share/timezone/Factory
   /usr/share/timezone/GB
   /usr/share/timezone/GB-Eire
   /usr/share/timezone/GMT
   /usr/share/timezone/GMT+0
   /usr/share/timezone/GMT-0
   /usr/share/timezone/GMT0
   /usr/share/timezone/Greenwich
   /usr/share/timezone/HST
   /usr/share/timezone/Hongkong
   /usr/share/timezone/Iceland
   /usr/share/timezone/Indian/Antananarivo
   /usr/share/timezone/Indian/Chagos
   /usr/share/timezone/Indian/Christmas
   /usr/share/timezone/Indian/Cocos
   /usr/share/timezone/Indian/Comoro
   /usr/share/timezone/Indian/Kerguelen
   /usr/share/timezone/Indian/Mahe
   /usr/share/timezone/Indian/Maldives
   /usr/share/timezone/Indian/Mauritius
   /usr/share/timezone/Indian/Mayotte
   /usr/share/timezone/Indian/Reunion
   /usr/share/timezone/Iran
   /usr/share/timezone/Israel
   /usr/share/timezone/Jamaica
   /usr/share/timezone/Japan
   /usr/share/timezone/Kwajalein
   /usr/share/timezone/Libya
   /usr/share/timezone/MET
   /usr/share/timezone/MST
   /usr/share/timezone/MST7MDT
   /usr/share/timezone/Mexico/BajaNorte
   /usr/share/timezone/Mexico/BajaSur
   /usr/share/timezone/Mexico/General
   /usr/share/timezone/NZ
   /usr/share/timezone/NZ-CHAT
   /usr/share/timezone/Navajo
   /usr/share/timezone/PRC
   /usr/share/timezone/PST8PDT
   /usr/share/timezone/Pacific/Apia
   /usr/share/timezone/Pacific/Auckland
   /usr/share/timezone/Pacific/Bougainville
   /usr/share/timezone/Pacific/Chatham
   /usr/share/timezone/Pacific/Chuuk
   /usr/share/timezone/Pacific/Easter
   /usr/share/timezone/Pacific/Efate
   /usr/share/timezone/Pacific/Enderbury
   /usr/share/timezone/Pacific/Fakaofo
   /usr/share/timezone/Pacific/Fiji
   /usr/share/timezone/Pacific/Funafuti
   /usr/share/timezone/Pacific/Galapagos
   /usr/share/timezone/Pacific/Gambier
   /usr/share/timezone/Pacific/Guadalcanal
   /usr/share/timezone/Pacific/Guam
   /usr/share/timezone/Pacific/Honolulu
   /usr/share/timezone/Pacific/Johnston
   /usr/share/timezone/Pacific/Kiritimati
   /usr/share/timezone/Pacific/Kosrae
   /usr/share/timezone/Pacific/Kwajalein
   /usr/share/timezone/Pacific/Majuro
   /usr/share/timezone/Pacific/Marquesas
   /usr/share/timezone/Pacific/Midway
   /usr/share/timezone/Pacific/Nauru
   /usr/share/timezone/Pacific/Niue
   /usr/share/timezone/Pacific/Norfolk
   /usr/share/timezone/Pacific/Noumea
   /usr/share/timezone/Pacific/Pago_Pago
   /usr/share/timezone/Pacific/Palau
   /usr/share/timezone/Pacific/Pitcairn
   /usr/share/timezone/Pacific/Pohnpei
   /usr/share/timezone/Pacific/Ponape
   /usr/share/timezone/Pacific/Port_Moresby
   /usr/share/timezone/Pacific/Rarotonga
   /usr/share/timezone/Pacific/Saipan
   /usr/share/timezone/Pacific/Samoa
   /usr/share/timezone/Pacific/Tahiti
   /usr/share/timezone/Pacific/Tarawa
   /usr/share/timezone/Pacific/Tongatapu
   /usr/share/timezone/Pacific/Truk
   /usr/share/timezone/Pacific/Wake
   /usr/share/timezone/Pacific/Wallis
   /usr/share/timezone/Pacific/Yap
   /usr/share/timezone/Poland
   /usr/share/timezone/Portugal
   /usr/share/timezone/ROC
   /usr/share/timezone/ROK
   /usr/share/timezone/Singapore
   /usr/share/timezone/Turkey
   /usr/share/timezone/UCT
   /usr/share/timezone/US/Alaska
   /usr/share/timezone/US/Aleutian
   /usr/share/timezone/US/Arizona
   /usr/share/timezone/US/Central
   /usr/share/timezone/US/East-Indiana
   /usr/share/timezone/US/Eastern
   /usr/share/timezone/US/Hawaii
   /usr/share/timezone/US/Indiana-Starke
   /usr/share/timezone/US/Michigan
   /usr/share/timezone/US/Mountain
   /usr/share/timezone/US/Pacific
   /usr/share/timezone/US/Pacific-New
   /usr/share/timezone/US/Samoa
   /usr/share/timezone/UTC
   /usr/share/timezone/Universal
   /usr/share/timezone/W-SU
   /usr/share/timezone/WET
   /usr/share/timezone/Zulu
   /usr/share/timezone/posixrules
   /usr/share/timezonesets/Africa.txt
   /usr/share/timezonesets/America.txt
   /usr/share/timezonesets/Antarctica.txt
   /usr/share/timezonesets/Asia.txt
   /usr/share/timezonesets/Atlantic.txt
   /usr/share/timezonesets/Australia
   /usr/share/timezonesets/Australia.txt
   /usr/share/timezonesets/Default
   /usr/share/timezonesets/Etc.txt
   /usr/share/timezonesets/Europe.txt
   /usr/share/timezonesets/India
   /usr/share/timezonesets/Indian.txt
   /usr/share/timezonesets/Pacific.txt
   /usr/share/tsearch_data/danish.stop
   /usr/share/tsearch_data/dutch.stop
   /usr/share/tsearch_data/english.stop
   /usr/share/tsearch_data/finnish.stop
   /usr/share/tsearch_data/french.stop
   /usr/share/tsearch_data/german.stop
   /usr/share/tsearch_data/hungarian.stop
   /usr/share/tsearch_data/hunspell_sample.affix
   /usr/share/tsearch_data/hunspell_sample_long.affix
   /usr/share/tsearch_data/hunspell_sample_long.dict
   /usr/share/tsearch_data/hunspell_sample_num.affix
   /usr/share/tsearch_data/hunspell_sample_num.dict
   /usr/share/tsearch_data/ispell_sample.affix
   /usr/share/tsearch_data/ispell_sample.dict
   /usr/share/tsearch_data/italian.stop
   /usr/share/tsearch_data/norwegian.stop
   /usr/share/tsearch_data/portuguese.stop
   /usr/share/tsearch_data/russian.stop
   /usr/share/tsearch_data/spanish.stop
   /usr/share/tsearch_data/swedish.stop
   /usr/share/tsearch_data/synonym_sample.syn
   /usr/share/tsearch_data/thesaurus_sample.ths
   /usr/share/tsearch_data/turkish.stop



%changelog
